name: PROD - Test and Deploy
on:
  push:
    branches:
      - main


jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG check ping to MAIL_TARGET_IP and HETZNER_TARGET_IP
        run: |
          echo "===> Pinging MAIL_TARGET_IP_DEV"
          ping -c 4 157.90.206.195
          
          echo "===> Pinging MAIL_TARGET_IP_PROD" 
          ping -c 4 5.9.147.156
          echo "===> Pinging HETZNER_TARGET_IP_PROD" 
          ping -c 4 157.90.206.208